// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCRUD_Clean.Infrastructure.Data;

#nullable disable

namespace ShoppingCRUD_Clean.Infrastructure.Migrations
{
    [DbContext(typeof(ShoppingDbContext))]
    [Migration("20240806163250_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("ShoppingCRUD_Clean.Domain.Entity.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShoppingListId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("ShoppingCRUD_Clean.Domain.Entity.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ShoppingListCategory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StarCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShoppingListItems");
                });

            modelBuilder.Entity("ShoppingCRUD_Clean.Domain.Entity.Item", b =>
                {
                    b.HasOne("ShoppingCRUD_Clean.Domain.Entity.ShoppingList", null)
                        .WithMany("Item")
                        .HasForeignKey("ShoppingListId");
                });

            modelBuilder.Entity("ShoppingCRUD_Clean.Domain.Entity.ShoppingList", b =>
                {
                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
